[{"commit":{"message":"graphKit: remove unneeded failure check in builtin_throw()\n\n`GraphKit::builtin_throw()` features a bailout check after getting an\nappropriate exception object. However, up to that point the execution in\n`builtin_throw()` cannot fail. In particular, there can be no failure to\nallocate the exception becuase these are all preallocated during\n`Threads::create_vm()` startup in `universe_post_init()` and\n`Threads:initialize_java_lang_classes()`. Further, none of the three\ncallers handles an (allegedly) possible bailout in `builtin_throw()`."},"files":[{"filename":"src\/hotspot\/share\/opto\/graphKit.cpp"}],"sha":"8ca6eef274509f903f9a16e7b12d888a3a1ea9b3"}]