[{"commit":{"message":"requests fixes\n\n- Use IOException.toString() instead of getMessage() in case it's empty\n- Attempts to test connect exceptions may fail due to unexpected\n  successful connect.  Tests quit with uncompleted status if the\n  connect is successful and are retried a small number of times until\n  the test can be performed properly.  If the retries are exceeded an\n  exception is generated indicating the test can't be setup properly."},"files":[{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/event\/SocketConnectFailedEvent.java"},{"filename":"src\/jdk.jfr\/share\/classes\/jdk\/jfr\/events\/SocketConnectFailedEvent.java"},{"filename":"test\/jdk\/jdk\/jfr\/event\/io\/IOHelper.java"},{"filename":"test\/jdk\/jdk\/jfr\/event\/io\/TestSocketAdapterEvents.java"},{"filename":"test\/jdk\/jdk\/jfr\/event\/io\/TestSocketChannelEvents.java"},{"filename":"test\/jdk\/jdk\/jfr\/event\/io\/TestSocketEvents.java"}],"sha":"5e55ffc6769ac8bab841522886385e2ba1ed8c34"}]