{"files":[{"patch":"@@ -61,1 +61,1 @@\n-  assert(!thread->preempting(), \"\");\n+  assert(!thread->preempting(), \"Unexpected Java upcall whilst processing preemption\");\n","filename":"src\/hotspot\/share\/runtime\/javaCalls.cpp","additions":1,"deletions":1,"binary":false,"changes":2,"status":"modified"},{"patch":"@@ -348,2 +348,2 @@\n-    \/\/ the exception is propagated we might make an upcall to\n-    \/\/ Java to initialize the object with the cause of exception.\n+    \/\/ the PreemptedException is propagated we might make an upcall\n+    \/\/ to Java to initialize the object with the cause of exception.\n","filename":"src\/hotspot\/share\/utilities\/exceptions.cpp","additions":2,"deletions":2,"binary":false,"changes":4,"status":"modified"}]}