{"files":[{"patch":"@@ -2,1 +2,1 @@\n- * Copyright (c) 2002, 2023, Oracle and\/or its affiliates. All rights reserved.\n+ * Copyright (c) 2002, 2024, Oracle and\/or its affiliates. All rights reserved.\n@@ -144,0 +144,10 @@\n+\n+    static public int[] trash;\n+\n+    void methodForException() {\n+        trash = new int[10];\n+        for (int i = 0; ;i++) {\n+            trash[i % trash.length] = i;\n+        }\n+    }\n+\n@@ -159,2 +169,3 @@\n-            \/\/ gets thrown before we leave the try block. Printing a log message works well.\n-            kill001a.log.display(\"exited synchronized\");\n+            \/\/ gets thrown before we leave the try block.\n+            \/\/ The methodForException should work until exception is thrown.\n+            methodForException();\n","filename":"test\/hotspot\/jtreg\/vmTestbase\/nsk\/jdb\/kill\/kill001\/kill001a.java","additions":14,"deletions":3,"binary":false,"changes":17,"status":"modified"}]}