{"files":[{"patch":"@@ -2,1 +2,1 @@\n- * Copyright (c) 2021, 2023, Oracle and\/or its affiliates. All rights reserved.\n+ * Copyright (c) 2021, 2025, Oracle and\/or its affiliates. All rights reserved.\n@@ -33,1 +33,0 @@\n-import org.testng.Assert;\n@@ -36,1 +35,0 @@\n-import java.io.IOException;\n@@ -47,2 +45,0 @@\n-import java.util.concurrent.TimeoutException;\n-import java.util.concurrent.TimeUnit;\n@@ -51,3 +47,0 @@\n-import static org.testng.Assert.assertTrue;\n-import static org.testng.Assert.assertNotNull;\n-import static org.testng.Assert.expectThrows;\n@@ -104,1 +97,1 @@\n-        for (var f : futures) {\n+        for (int i = 0; i < futures.size(); i++) {\n@@ -106,1 +99,1 @@\n-                f.get();\n+                futures.get(i).get();\n@@ -109,1 +102,2 @@\n-                e.getCause().printStackTrace(System.out);\n+                System.err.println(\"task \" + (i + 1) + \" failed:\");\n+                e.getCause().printStackTrace();\n@@ -122,2 +116,1 @@\n-            String msg = e.getCause() == null ? e.getMessage() : e.getCause().getMessage();\n-            System.err.println(\"MSG RTE: \" + msg);\n+            final String msg = e.getCause() == null ? e.getMessage() : e.getCause().getMessage();\n@@ -125,3 +118,10 @@\n-            assertNotNull(msg);\n-            assertTrue(msg.contains(\"Network is unreachable\")\n-                        || msg.contains(\"No route to host\") || msg.contains(\"Connection timed out\"));\n+            if (msg != null &&\n+                    (msg.contains(\"Network is unreachable\")\n+                            || msg.contains(\"No route to host\")\n+                            || msg.contains(\"Connection timed out\"))) {\n+                \/\/ got the expected exception\n+                System.out.println(\"Received expected RuntimeException message: \" + msg);\n+            } else {\n+                \/\/ propagate the unexpected exception\n+                throw e;\n+            }\n@@ -129,3 +129,2 @@\n-            String msg = ex.getCause() == null ? ex.getMessage() : ex.getCause().getMessage();\n-            System.err.println(\"MSG: \" + msg);\n-            assertTrue(msg != null &&\n+            final String msg = ex.getCause() == null ? ex.getMessage() : ex.getCause().getMessage();\n+            if (msg != null &&\n@@ -135,1 +134,7 @@\n-                        || msg.contains(\"Timeout exceeded while waiting for a connection\")));\n+                        || msg.contains(\"Timeout exceeded while waiting for a connection\"))) {\n+                \/\/ got the expected exception\n+                System.out.println(\"Received expected NamingException message: \" + msg);\n+            } else {\n+                \/\/ propagate the unexpected exception\n+                throw ex;\n+            }\n","filename":"test\/jdk\/com\/sun\/jndi\/ldap\/LdapPoolTimeoutTest.java","additions":25,"deletions":20,"binary":false,"changes":45,"status":"modified"}]}