[{"commit":{"message":"8313626: C2 crash due to unexpected exception control flow\n\nBackport-of: f8203cb272e6136b784e5c43a500f6a0bfb19c8b"},"files":[{"filename":"hotspot\/src\/share\/vm\/opto\/doCall.cpp"},{"filename":"hotspot\/test\/compiler\/parsing\/MissingSafepointOnTryCatch.jasm"},{"filename":"hotspot\/test\/compiler\/parsing\/TestMissingSafepointOnTryCatch.java"}],"sha":"82de5421870c671b0bc4f90064a24d7bbfd361e0"}]