{"files":[{"patch":"@@ -116,1 +116,5 @@\n-                    savedCSE = cse;\n+                    if (savedCSE == null) {\n+                        savedCSE = cse;\n+                    } else {\n+                        savedCSE.addSuppressed(cse);\n+                    }\n@@ -193,1 +197,5 @@\n-                savedCSE = cse;\n+                if (savedCSE == null) {\n+                    savedCSE = cse;\n+                } else {\n+                    savedCSE.addSuppressed(cse);\n+                }\n","filename":"src\/java.base\/share\/classes\/sun\/security\/provider\/certpath\/DistributionPointFetcher.java","additions":10,"deletions":2,"binary":false,"changes":12,"status":"modified"},{"patch":"@@ -34,0 +34,1 @@\n+import java.security.cert.CertPathValidatorException.BasicReason;\n@@ -53,0 +54,1 @@\n+import sun.security.x509.X509CRLEntryImpl;\n@@ -62,1 +64,2 @@\n- *          behavior whether CRL cache is fresh or stale.\n+ *          behavior (fails because cert is revoked) whether CRL cache is\n+ *          fresh or stale.\n@@ -101,0 +104,2 @@\n+        System.out.println(\"Validating cert with CRLDP containing one \"\n+            + \"DistributionPoint with 2 entries, the first non-existent\");\n@@ -104,0 +109,2 @@\n+        System.out.println(\"Validating cert with CRLDP containing two \"\n+            + \"DistributionPoints with 1 entry each, the first non-existent\");\n@@ -168,0 +175,4 @@\n+        \/\/ revoke cert\n+        X509CRLEntryImpl crlEntry =\n+            new X509CRLEntryImpl(new BigInteger(\"1\"), new Date());\n+\n@@ -172,1 +183,1 @@\n-            new Date(end), null, crlExts);\n+            new Date(end), new X509CRLEntryImpl[]{ crlEntry }, crlExts);\n@@ -212,1 +223,1 @@\n-            System.out.println(\"Validation passed as expected\");\n+            throw new Exception(\"Validation passed unexpectedly\");\n@@ -214,1 +225,4 @@\n-            throw new Exception(\"Validation should have passed\", cpve);\n+            if (cpve.getReason() != BasicReason.REVOKED) {\n+                throw new Exception(\"Validation failed with unexpected reason\", cpve);\n+            }\n+            System.out.println(\"Validation failed as expected: \" + cpve);\n","filename":"test\/jdk\/java\/security\/cert\/CertPathValidator\/crlDP\/CheckAllCRLs.java","additions":18,"deletions":4,"binary":false,"changes":22,"status":"modified"}]}