{"files":[{"patch":"@@ -31,0 +31,6 @@\n+\/\/ This method exit callback actually works only for 2 methods:\n+\/\/ 1) for ExceptionExit it verifies that method exit\n+\/\/    has been popped by exception and call 'upCall' mthod using JNI.\n+\/\/ 2) for upCall method it verifies that event has correct\n+\/\/    return value and was not popped by execption.\n+\/\/ The event callback just exits for all other methods.\n@@ -52,1 +58,3 @@\n-\n+  if (!was_popped_by_exception) {\n+    fatal(jni, \"Should have was_popped_by_esxception = true.\");\n+  }\n@@ -58,2 +66,2 @@\n-\n-  jmethodID upcall_method = jni->GetStaticMethodID(main_class, \"upCall\", \"()Ljava\/lang\/String;\");\n+  jmethodID upcall_method = jni->GetStaticMethodID(main_class,\n+      \"upCall\", \"()Ljava\/lang\/String;\");\n@@ -63,0 +71,2 @@\n+  \/\/ Call 'upCall' method while current thread has exception\n+  \/\/ that has been thrown but hasn't been caught yet.\n","filename":"test\/hotspot\/jtreg\/serviceability\/jvmti\/events\/MethodExit\/ExceptionOccurred\/libExceptionOccurred.cpp","additions":13,"deletions":3,"binary":false,"changes":16,"status":"modified"}]}