[{"commit":{"message":"8333812: ClassFile.verify() can throw exceptions instead of returning VerifyErrors"},"files":[{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/classfile\/impl\/BoundAttribute.java"},{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/classfile\/impl\/verifier\/VerifierImpl.java"},{"filename":"test\/jdk\/jdk\/classfile\/VerifierSelfTest.java"}],"sha":"32476edfd521533582e27cb6eb809837e9b91b22"}]